### Create a new patient entity

POST http://localhost:4000/patients
Content-Type: application/json

{
"name":"Sathyajith Saliya",
"email":"hmsathyajith@gmail.com",
"dateOfBirth":"1996-11-27",
"address":"178/5/1/A, Utuwankanda Rd, Thalwathugoda",
"registeredDate":"2025-10-21"
 }